#!/usr/bin/env python3
"""Generate test prints for printsim's support analysis.

  samples/mushroom-no-supports.gcode  a stem with a wide flat cap and NO supports:
                                      the cap will print in mid-air (should fail)
  test/bridge.gcode                   two pillars joined by a bridge (should NOT fail)

MINI-style start G-code, ;TYPE:/;WIDTH: comments and M73 markers, same as
make_sample.py. Not meant to be printed.
"""
import math
import os

W = 0.45
LH = 0.2
FIL_AREA = math.pi * (1.75 / 2) ** 2
CX = CY = 90.0


class G:
    def __init__(self):
        self.lines = []
        self.pos = [0.0, 0.0, 0.0]
        self.t = 0.0
        self.f = 20.0

    def emit(self, s):
        self.lines.append(s)

    def _move(self, x, y, z, e, f):
        parts = ['G1']
        if x is not None: parts.append(f'X{x:.3f}')
        if y is not None: parts.append(f'Y{y:.3f}')
        if z is not None: parts.append(f'Z{z:.3f}')
        if e is not None: parts.append(f'E{e:.5f}')
        if f is not None:
            parts.append(f'F{f * 60:.0f}')
            self.f = f
        n = [self.pos[0] if x is None else x, self.pos[1] if y is None else y, self.pos[2] if z is None else z]
        d = math.dist(self.pos, n) or (abs(e) if e else 0)
        self.t += d / self.f + 0.002
        self.pos = n
        self.emit(' '.join(parts))

    def travel(self, x, y, z=None):
        self._move(None, None, None, -0.7, 35)
        if z is not None:
            self._move(None, None, z + 0.2, None, 12)
        self._move(x, y, None, None, 150)
        if z is not None:
            self._move(None, None, z, None, 12)
        self._move(None, None, None, 0.7, 25)

    def path(self, pts, speed, h=LH):
        self._move(None, None, None, None, speed)
        for (x, y) in pts:
            d = math.dist(self.pos[:2], (x, y))
            self._move(x, y, None, d * W * h / FIL_AREA, None)

    def layer(self, z, h):
        self.emit(';LAYER_CHANGE')
        self.emit(f';Z:{z:.2f}')
        self.emit(f';HEIGHT:{h}')


def circle(r, n=None, cx=CX, cy=CY):
    n = n or max(24, int(2 * math.pi * r / 0.8))
    return [(cx + r * math.cos(2 * math.pi * i / n), cy + r * math.sin(2 * math.pi * i / n)) for i in range(n)] + \
           [(cx + r, cy)]


def rect(x0, y0, x1, y1):
    return [(x0, y0), (x1, y0), (x1, y1), (x0, y1), (x0, y0)]


def zigzag_circle(r, spacing, angle):
    ca, sa = math.cos(angle), math.sin(angle)
    out, fwd = [], True
    k = -r + spacing / 2
    while k < r:
        half = math.sqrt(max(r * r - k * k, 0))
        if half > 0.5:
            a, b = (-half, k), (half, k)
            if not fwd:
                a, b = b, a
            for (u, v) in (a, b):
                out.append((CX + u * ca - v * sa, CY + u * sa + v * ca))
            fwd = not fwd
        k += spacing
    return out


def zigzag_rect(x0, y0, x1, y1, spacing, along_x=True):
    out, fwd = [], True
    if along_x:
        y = y0 + spacing / 2
        while y < y1:
            a, b = ((x0, y), (x1, y)) if fwd else ((x1, y), (x0, y))
            out += [a, b]
            fwd = not fwd
            y += spacing
    else:
        x = x0 + spacing / 2
        while x < x1:
            a, b = ((x, y0), (x, y1)) if fwd else ((x, y1), (x, y0))
            out += [a, b]
            fwd = not fwd
            x += spacing
    return out


def disk_layer(g, z, r, solid, n):
    g.travel(*circle(r - W)[0], z=z)
    g.emit(';TYPE:Perimeter'); g.emit(f';WIDTH:{W}')
    g.path(circle(r - W), 40)
    g.travel(*circle(r)[0])
    g.emit(';TYPE:External perimeter')
    g.path(circle(r), 30)
    fill = zigzag_circle(r - 1.5 * W, W if solid else 2.2, (math.pi / 4) * (1 if n % 2 else -1))
    if fill:
        g.travel(*fill[0])
        g.emit(';TYPE:Solid infill' if solid else ';TYPE:Internal infill')
        g.path(fill[1:], 60 if solid else 90)


def rect_layer(g, z, box, solid, n, along_x=None):
    x0, y0, x1, y1 = box
    g.travel(x0 + W, y0 + W, z=z)
    g.emit(';TYPE:Perimeter'); g.emit(f';WIDTH:{W}')
    g.path(rect(x0 + W, y0 + W, x1 - W, y1 - W)[1:], 40)
    g.travel(x0, y0)
    g.emit(';TYPE:External perimeter')
    g.path(rect(x0, y0, x1, y1)[1:], 30)
    ax = (n % 2 == 0) if along_x is None else along_x
    fill = zigzag_rect(x0 + 1.5 * W, y0 + 1.5 * W, x1 - 1.5 * W, y1 - 1.5 * W, W if solid else 2.2, ax)
    if fill:
        g.travel(*fill[0])
        g.emit(';TYPE:Bridge infill' if along_x is not None else (';TYPE:Solid infill' if solid else ';TYPE:Internal infill'))
        g.path(fill[1:], 60)


def header(total, name, zmax, colour):
    return f"""; generated by printsim tools/make_overhang_tests.py ({name})

; printer_model = MINI
; filament_type = PLA
; layer_height = {LH}
; max_layer_z = {zmax}
; filament_colour = {colour}
; support_material = 0
; estimated printing time (normal mode) = {int(total // 60)}m {int(total % 60)}s

M201 X2500 Y2500 Z400 E5000
M203 X180 Y180 Z12 E80
M204 P1250 R1250 T1250
M205 X8.00 Y8.00 Z2.00 E10.00
;TYPE:Custom
G90
M83
M104 S170
M140 S60
M109 R170
M190 S60
G28
G29
M104 S215
G92 E0
G1 Z0.2 F720
G1 Y-3 F1000
M109 S215
G1 X60 E9 F1000
G1 X100 E12.5 F1000
G92 E0
"""


def with_m73(g):
    total = g.t
    # replay timings via the recorded order: approximate by line index share of time
    out, t, last = [], 0.0, -1
    # recompute per-line time
    pos, f = [0.0, 0.0, 0.0], 20.0
    import re
    rx = re.compile(r'([XYZEF])(-?\d*\.?\d+)')
    for line in g.lines:
        if line.startswith('G1'):
            v = {k: float(n) for k, n in rx.findall(line)}
            if 'F' in v: f = v['F'] / 60
            n = [v.get('X', pos[0]), v.get('Y', pos[1]), v.get('Z', pos[2])]
            d = math.dist(pos, n) or abs(v.get('E', 0))
            t += d / f + 0.002
            pos = n
        p = int(t / total * 100)
        if p != last and p < 100:
            out.append(f'M73 P{p} R{math.ceil((total - t) / 60)}')
            last = p
        out.append(line)
    out.append('M73 P100 R0')
    return total, out


def mushroom():
    g = G()
    z, n = LH, 0
    STEM_R, CAP_R, STEM_TOP, CAP_TOP = 7.0, 24.0, 12.0, 17.0
    while z <= CAP_TOP + 1e-6:
        g.layer(z, LH)
        if z <= STEM_TOP:
            disk_layer(g, z, STEM_R, n < 3, n)
        else:
            # flat cap for 1.4 mm, then a dome closing up
            k = (z - STEM_TOP) / (CAP_TOP - STEM_TOP)
            r = CAP_R if k < 0.3 else CAP_R * math.sqrt(max(0.05, 1 - ((k - 0.3) / 0.7) ** 2))
            disk_layer(g, z, max(r, 3), (z - STEM_TOP) < 0.9 or z > CAP_TOP - 0.7, n)
        z = round(z + LH, 3)
        n += 1
    return g, CAP_TOP


def bridge():
    g = G()
    z, n = LH, 0
    A = (60.0, 84.0, 72.0, 96.0)
    B = (98.0, 84.0, 110.0, 96.0)   # 26 mm gap between pillars
    SLAB = (60.0, 84.0, 110.0, 96.0)
    while z <= 12.0 + 1e-6:
        g.layer(z, LH)
        if z <= 10.0:
            rect_layer(g, z, A, n < 3, n)
            rect_layer(g, z, B, n < 3, n)
        else:
            first = z <= 10.2 + 1e-6
            rect_layer(g, z, SLAB, True, n, along_x=True if first else None)
        z = round(z + LH, 3)
        n += 1
    return g, 12.0


root = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..')
for name, fn, path, colour in [
    ('mushroom, no supports', mushroom, 'samples/mushroom-no-supports.gcode', '#E8E2D0'),
    ('bridge test', bridge, 'test/bridge.gcode', '#1F6FEB'),
]:
    g, zmax = fn()
    total, lines = with_m73(g)
    full = os.path.join(root, path)
    os.makedirs(os.path.dirname(full), exist_ok=True)
    with open(full, 'w') as fh:
        fh.write(header(total, name, zmax, colour))
        fh.write('\n'.join(lines) + '\n')
        fh.write(';TYPE:Custom\nG1 Z30 F720\nM104 S0\nM140 S0\nM84\n')
    print(path, len(lines), 'lines', f'{total/60:.1f} min')
